# Generated by Django 5.1.2 on 2024-11-04 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_manager', '0002_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='owner',
            new_name='folderuser',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='folderdesc',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='foldername',
            field=models.CharField(default='Default Folder Name', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetitle', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Files')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_manager.folder')),
            ],
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
